# Generated by Django 5.0.2 on 2024-07-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_expiry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
