# Generated by Django 5.0.2 on 2024-07-10 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_alter_payment_card_expiry_alter_payment_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myuser.payment'),
            preserve_default=False,
        ),
    ]
