# Generated by Django 5.0.2 on 2024-06-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='username',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packages',
            name='price',
            field=models.IntegerField(),
        ),
    ]
