# Generated by Django 5.0.2 on 2024-06-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_packages_days_packages_image_packages_nights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='destination',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='date',
        ),
    ]
