# Generated by Django 5.0.2 on 2024-06-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_rename_destination_packages_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='username',
        ),
    ]
