# Generated by Django 5.0.2 on 2024-06-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_remove_packages_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='image',
        ),
    ]
