# Generated by Django 5.0.2 on 2024-06-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_alter_packages_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='person',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
