# Generated by Django 5.0.2 on 2024-07-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_packages_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='description',
            field=models.CharField(max_length=750),
        ),
    ]
